PS\Bundle\PSPointsBundle\Entity\Points:
    type: entity
    table: points
    repositoryClass: PS\Bundle\PSPointsBundle\Entity\PointsRepository
    indexes:
        about_index:
          columns: [about]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        creationDate:
            type: datetime
        source:
            type: string
            length: '20'
        points:
            type: integer
        about:
            type: string
            length: 255
    lifecycleCallbacks: {  }
