parameters:
   psps.points.api.supported_formats: json|xml

services:
    psps.points.manager:
        class: PS\Bundle\PSPointsBundle\Model\PointsManager
        arguments: [ @doctrine.orm.entity_manager, @event_dispatcher]

    psps.user_asocciation.listener:
        class: PS\Bundle\PSPointsBundle\Doctrine\ORM\EventListener\UserAssociationListener
        arguments: [ %psps.user_class%]
        public: false
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata}

    psps.user_add_points.listener:
        class: PS\Bundle\PSPointsBundle\EventListener\PointsListener
        arguments: [ @psps.points.manager]
        tags:
            - { name: kernel.event_listener, event: psps.points.event.post_persist_points, method: onSavePoints }