parameters:
   psps.points.api.supported_formats: json|xml

services:
    psps.points.manager:
        class: PS\Bundle\PSPointsBundle\Model\PointsManager
        arguments: [ @doctrine.orm.entity_manager]

    psps.user_asocciation.listener:
        class: PS\Bundle\PSPointsBundle\Doctrine\ORM\EventListener\UserAssociationListener
        arguments: [ %psps.user_class%]
        public: false
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata}